ProyectoIntegrador2018/arquidiocesis-back

- index.js
- package-lock.json
- package.json
- routes/grupo.js
- routes/parroquia.js
> Integrantes s2

- index.js
- routes/admin.js
- routes/login.js
Added get admins, getone admin, edit admin, delete admin, register admin.
Added check to see if the user can access admin actions (ONLY admin actions).
> Admin endpoints

- index.js
- routes/admin.js
- routes/capacitacion.js
- routes/coordinadores.js
- routes/grupo.js
Moved coordinadores and admins to separate collections.
> Moved miembros to separate collections

- index.js
- routes/acompanantes.js
Get, remove, add y edit de acompañantes.
> Get, add and remove acompañantes

- index.js
- routes/participante.js
> Adds Edit Participante

- package.json
- routes/all.js
- routes/capacitacion.js
- routes/capillas.js
- routes/coordinadores.js
- routes/decanato.js
- routes/grupo.js
- routes/parroquia.js
- routes/participante.js
- routes/util.js
FF-05 - Fecha de creación de grupo/capacitacion, fecha de registro de miembros.
FF-06 - Reportes en XLS
FF-04 - Info de parroquia/capilla y decanato de coordinador
> Final fixes

- index.js
- routes/acompanantes.js
1. Add queries to render a view of acompanantes and zone or decanato
Closes none.
> feat(acompanantes): add queries to get all and place info

- routes/all.js
- routes/coordinadores.js
- routes/parroquia.js
> D005 - Add custom id support to coordinadores and parroquias

- routes/grupo.js
1. Agrega medio electronico al backend
Closes none.
> Fix medio electronico

- routes/acompanantes.js
> fix(acompanantes): view decanato related

- routes/acompanantes.js
- routes/all.js
- routes/grupo.js
> feat(reports): generate reports for zonas and decanatos

- routes/acompanantes.js
- routes/coordinadores.js
- routes/parroquia.js
> Edit internal ids

- README.md
> docs(readme): include previous team members

- package.json
> chore(package.json): bump version

- index.js
- routes/estadisticas.js
- routes/grupo.js
1. Adds GetEstadisticas function to process all the statistics that the client required.
Closes none.
> Feat statistics

- index.js
- routes/eventos.js
1. Se crearon 4 metodos: el de obtener todos los eventos, agregar un evento, remover un evento y editar un evento
Closes none.
> Add calendar

- index.js
- routes/admin.js
- routes/all.js
- routes/capacitacion.js
- routes/capillas.js
- routes/coordinadores.js
- routes/grupo.js
- routes/login.js
- routes/parroquia.js
> Feat user roles

- index.js
- routes/objetivos.js
1. Se crearon endpoints para obtener y modificar objetivos de cada deecanato.
Closes none.
> feat(objetivos): se crearon endpoints en un nuevo archivo objetivos.js

- routes/objetivos.js
> fix(objetivos): fix typo when returning data

- package.json
> chore(release): v1.3.0 [skip ci]

- routes/eventos.js
> fix(events): give all users access to get all events

- yarn.lock
> build(yarn): updated yarn lockfile

- index.js
> fix(objetivos): replace patch with post method

- index.js
- routes/eventos.js
> fix(eventos): add dump for eventos report

- routes/capacitacion.js
> fix(capacitacion dump): fix capacitacion report

- .eslintrc.yml
- .github/workflows/node-build.yml
- .prettierignore
- .prettierrc.yml
- package.json
- yarn.lock
Installs and configures ESLint with Prettier for static analysis and automatic code formatting.
Closes none.
> style(linters): installed and configured eslint with prettier

- .eslintrc.yml
- .prettierrc.yml
- package.json
- yarn.lock
As stated in title.
Closes none.
> style(lints): added eslint and prettier pre-commit hooks

- .eslintrc.yml
Adds a few rules to improve static analysis.
Closes none.
> style(strict-eslint): reinforce eslint rules for safer code

- package.json
- scripts/user-table-migration.js
1. Adds script that performs the migration of relevant user information to a single table called user.
2. Adds command to execute the script explained above.
Closes none.
> User table creation migration

- __tests__/roles.spec.js
- index.js
- package.json
- routes/admin.js
- routes/all.js
- routes/capacitacion.js
- routes/capillas.js
- routes/eventos.js
- routes/grupo.js
- routes/parroquia.js
- routes/roles.js
- scripts/user-table-migration.js
- yarn.lock
- Added roles collection that stores all possible roles within the app.
- Added backend endpoints to add, add members or get all roles documents.
- Added test suite for roles functionalities, all passed.
- Added roles to index.js
1. Add roles functionality to the backend. This will let us work on further group, channels, posts features.
2. Roles functionalities are important to maintain permissions hierarchy in groups, channels and posts.
Closes none.
> Added roles functionality to backend.

- __tests__/canal.spec.js
- package.json
- routes/canal.js
- yarn.lock
1. Se agrego el back para canales con los metodos de crear y modificar.
2. Se agregaron prubas unitarias para los metodos de canales.
Closes la creacion del backen de canales.
> Se agrego canal y sus pruebas para comprobar su funcionamiento.

- __tests__/publicacion.spec.js
- routes/publicacion.js
1. Added post entity into the backend schema
2. Added posts functionalities in the backend
3. Added testsuite to check correct flow for posts feature
Closes none.
> Posts feature

- __tests__/grupo-conv.spec.js
- index.js
- routes/grupo-conv.js
1. Added getall functionality and test case for correct use.
2. Changed grupo-conv to grupo_conv.
Closes none.
> Added getall functionality to grupo-conv feature.

- index.js
1. Fixed role route name in index.js
2. Added channel routes to index.js
Closes none.
> Added channel routes to index.js

- routes/grupo-conv.js
1. Added default channel creation process on group creation.
Closes none.
> Add default channel on group creation

- routes/grupo-conv.js
1.Deleted default channel embedded creation.
Closes none.
> Deleted default channel embedded creation.

- __tests__/roles.spec.js
- routes/roles.js
1.Added revoke role function.
2.Added revoke role function tests.
Closes none.
> Revoke role

- __tests__/roles.spec.js
- routes/roles.js
1. Added remove role function.
2. Added remove role function tests.
Closes none.
> Added remove function for roles

- __tests__/grupo-conv.spec.js
- routes/grupo-conv.js
1. Added add members to a group conversation.
Closes none.
> Added add member function to group conversations

- __tests__/grupo-conv.spec.js
- routes/grupo-conv.js
1. Added remove one or multiple members from a group conversation.
Closes none.
> Group conv remove user

- __tests__/publicacion.spec.js
- index.js
- routes/publicacion.js
1. Added comentario de index.js
2. Added getChannelPosts to publicacion
3. Added tests to publication test suite (work as expected)
Closes none.
> Posts modifications

- __tests__/comentario.spec.js
- routes/comentario.js
1. Added comment feature.
2. Posts can have N-comments.
3. Test suite for comments was added (working properly and as expected).
Closes none.
> Added comment feature.

- __tests__/grupo-conv.spec.js
- __tests__/roles.spec.js
- routes/grupo-conv.js
- routes/roles.js
1.Added getAllRoleUsers to role.js; this will enable retrieving all users from a certain role.
2.Added addAdmin, addMembers, removeAdmin, removeMembers and their tests (work as expected).
Closes none.
> Roles and Grupo-conv feature additions

- .eslintrc.yml
- __tests__/login.spec.js
- jsconfig.json
- package.json
- routes/login.js
- yarn.lock
Fixes the new user info query in login.
Closes none.
> fix(user-login): user info query

- index.js
1. Added getAllRoleUsers to index.js from role.js
2. Added addAdmin,addMember,removeAdmin,removeMember to index.js from grupo-conv.js
Closes none.
> Add new role and grupo-conv routes to index.js

- __tests__/grupo-conv.spec.js
- index.js
- routes/grupo-conv.js
1. Fixed routes in index.js
2. Changed body to params in getAllRoleUsers
3. Fixed test for grupo-conv
Closes none.
> Fixed index.js routes

- routes/login.js
Now returns user ID on login query.
Closes none.
> fix(user-login): return id in new user info query

- routes/grupo-conv.js
1. Fixed get all groups by user
Closes none.
> fixed getAllGroups

- index.js
- routes/canal.js
1. Added getAllChannelByGroup feature
Closes none.
> add getAllChannelByGroup

- routes/canal.js
- routes/grupo-conv.js
1. Added documents id in groups retrieval
2. added documents id in channels retrieval
Closes none.
> additions to grupo-conv and canal

- routes/comentario.js
- routes/publicacion.js
1. Added document ids to post and comments retrieval
Closes none.
> Post additions

- __tests__/user.spec.js
- routes/grupo-conv.js
- routes/roles.js
- routes/user.js
1.Added user remove groups and roles functions.
Closes none.
> test(users): added new tests for users

- __tests__/publicacion.spec.js
- index.js
- routes/publicacion.js
1. Populates author info in posts by channel response
Closes none.
> feat(posts): add post author to get posts by channel endpoint

- __tests__/user.spec.js
- routes/grupo-conv.js
- routes/user.js
1.Added addGroupMembers to user.js
-Added test for the above feature (works as expected).
2.Fixed some errors in user.js
-Ran tests to check proper execution.
Closes none.
> Added addGroupMembers to user.js

- index.js
- routes/user.js
1.Added getAllUsers on user.js
Closes none.
> Added getAllUsers

- __tests__/grupo-conv.spec.js
- routes/grupo-conv.js
1. Change name of variable of members to group_members
Closes none.
> fix(group-conv): modified variable name

- __tests__/comentario.spec.js
- index.js
- routes/comentario.js
1. Use params instead of body in get post comments endpoint.
2. Return author info in get post comments endpoint.
3. Modify test for new response shape in get post comments endpoint
Closes none.
> fix(post-comments): fix route and response for get comments endpoint

- __tests__/grupo-conv.spec.js
- __tests__/roles.spec.js
- index.js
- routes/grupo-conv.js
- routes/roles.js
- routes/user.js
1. Adds functionality on user groups
2. Fixed several bugs on group operations
Closes none.
> Group add view fix 2

- routes/comentario.js
- routes/publicacion.js
1. Modified timestamp in post and comment creation.
Closes none.
> feat(timestamp-feature): modified timestamp in

- __tests__/user.spec.js
- routes/user.js
1. Added fix to fixed size limit in firestore retrival query
-This is done in users.js
Closes none.
> Fixed size limit in firestore retrieval query.

- routes/user.js
> fix(require): remove prettier import

- __tests__/publicacion.spec.js
- index.js
- package.json
- routes/filesUtil.js
- routes/publicacion.js
- scripts/file-manipulation.js
- yarn.lock
1. added create and delete functions to files feature.
Closes none.
> feat(files-feature-p1): added files creation

- index.js
- routes/canal.js
- routes/grupo-conv.js
1. Added delete feature to channels and grupo-conv
Closes none.
> Delete item feature

- routes/canal.js
- routes/comentario.js
- routes/grupo-conv.js
- routes/publicacion.js
- routes/util.js
1. Added notification triggers to creation and editing of posts, channels and comments.
Closes none.
> feat(notif-implementation): added notificacion to new components

- routes/acompanantes.js
- routes/admin.js
- routes/coordinadores.js
- routes/user.js
- scripts/user-table-migration.js
1.Connected useres table to every register of a user
Closes none.
> Register to user table

- index.js
- routes/filesUtil.js
1. Added CORS config to google cloud storage.
Closes none.
> feat(cors-config): added cors config to gcloud

- routes/acompanantes.js
- routes/canal.js
- routes/coordinadores.js
- routes/grupo-conv.js
1.Fixed backend functions of firebase
Closes none.
> fix(firebase-methods): fixed functions

- routes/canal.js
- routes/grupo-conv.js
> Firebase methods fix

- index.js
- routes/filesUtil.js
- routes/login.js
1. Fix file upload endpoint
2. Increase body payload limit for requests
Closes none.
> fix(files): fix file upload endpoint

- package.json
- routes/grupo-conv.js
- yarn.lock
1. added icon in backend
Closes none.
> feat(icon): added icon in backend

- __tests__/publicacion.spec.js
- index.js
- routes/canal.js
- routes/comentario.js
- routes/grupo-conv.js
- routes/publicacion.js
- routes/util.js
1. Add mising await to notification triggers.
2. Adjust notification path to match frontend's deeplinks
3. Fix Google Cloud Storage service key not working in production mode
Closes none.
> Adjust notifications parameters

- __tests__/comentario.spec.js
- routes/comentario.js
> fix(comments): fix invalid property access in comments add endpoint
